version: '3.8'
services:
  eterrain-tf-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: terraform-backend-service:latest
    container_name: terraform-backend
    ports:
      - "${HOST_PORT:-7777}:7777"
    environment:
      - HOST=0.0.0.0
      - PORT=7777
      - STORAGE_TYPE=${STORAGE_TYPE:-csv}
      - STORAGE_PATH=/app/data
      - ENABLE_TLS=${ENABLE_TLS:-false}
      - TLS_CERT_FILE=${TLS_CERT_FILE:-}
      - TLS_KEY_FILE=${TLS_KEY_FILE:-}
    volumes:
      # Persist data directory
      - ./data:/app/data
      # Mount auth configuration (read-only)
      - ./auth.cfg:/app/auth.cfg:ro
      # Optional: Mount TLS certificates if needed
      # - ./certs:/app/certs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7777/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    networks:
      - terraform-backend-net
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    # Security options
    security_opt:
      - no-new-privileges:true
    read_only: false
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  terraform-backend-net:
    driver: bridge
